site_name: SceneForge Studio
repo_url: https://github.com/MidnightCoffeeInc/SceneForge-Alpha-Test
repo_name: Download the Alpha
edit_uri: ""
nav:
    - Home: index.md
    - Getting Started: gettingStarted.md
    - Scene Controls: sceneControls.md
    - The Camera: cameras.md
    - Rigged Characters: characters.md
    - Storyboards: storyboards.md
    - Known Issues: issues.md
theme:
  name: 'material'
  #custom_dir: overrides
  palette:
    scheme: 'slate'
    primary: deep purple
  font:
    text: Open-Sans
    code: Roboto Mono
  features:
    - navigation.tabs
  logo:
    img/SceneforgeLogo.png
  favicon:
    img/SceneforgeLogo.png

  icon:
    repo: fontawesome/brands/github
  hide:
    - navigation # Hide navigation

markdown_extensions:
  - attr_list